### ISSUE TITLE
Train, test split on OpenML data

### ISSUE THREAD

**Issue by pplonski** [Innixma/autogluon-benchmarking#2]
I would like to run my [AutoML package](https://github.com/mljar/mljar-supervised) on the same train/test split of OpenML datasets. Could you please give some instructions on how to obtain exact split for train/test?

**Comment by Innixma** [comment]
Hi @pplonski, 

The easiest way to run the OpenML datasets would be to use automlbenchmark as done in our paper: https://github.com/openml/automlbenchmark

By running through automlbenchmark, it will automatically get the same train/test splits as in our paper, as they are predefined.

All you need to do is create a framework wrapper for your AutoML package in automlbenchmark, and it should work for you.

Here is the issue open regarding adding AutoGluon officially to automlbenchmark, which you could consider going a similar path: https://github.com/openml/automlbenchmark/issues/93

Hope this helps!

**Comment by pplonski** [comment]
Thank you Nick!
